server:
  port: 8080

spring:
  jpa:
    show-sql: true
  messages:
    basename: messages

logging:
  level:
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"