server:
  port: 8080

spring:
  jpa:
    show-sql: true
  messages:
    basename: messages

  h2:
    console:
      enabled: true

#logging:
#  level:
#    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"